### ISSUE TITLE
Can't use the add on

### ISSUE THREAD

**Issue by filipedribeiro** [Arthur-Milchior/Anki-postpone-reviews#14]
I keep getting the following issue:

```
Informação de Debug:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-28 18:16:10

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Filipe\AppData\Roaming\Anki2\addons21\1152543397\addToMain.py", line 17, in <lambda>
    addToMain(lambda: addDelay(getReviewCards()), _("Postpone cards"))
  File "C:\Users\Filipe\AppData\Roaming\Anki2\addons21\1152543397\addDay.py", line 30, in getReviewCards
    cids = mw.col.find_cards("is:review")
AttributeError: '_Collection' object has no attribute 'find_cards'

```

**Comment by filipedribeiro** [comment]
I had to update Anki itself. Sorry about that!

**Comment by Arthur-Milchior** [comment]
That's corrected. It should now work with all version of anki. Sorry that I didn't realize before that the last change was not compatible with recent version of anki
