### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'aqt.hooks_gen' in Anki 2.1.55 beta 5

### ISSUE THREAD

**Issue by L-M-Sherlock** [Arthur-Milchior/Anki-postpone-reviews#32]
When I update to the Anki 2.1.55 beta 5, the add-on breaks up.

```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Postpone cards review⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/jarrettye/Library/Application Support/Anki2/addons21/1152543397/__init__.py", line 1, in <module>
    from . import addToBrowser, addToGear, addToMain
  File "/Users/jarrettye/Library/Application Support/Anki2/addons21/1152543397/addToGear.py", line 2, in <module>
    from aqt.hooks_gen import deck_browser_will_show_options_menu
ModuleNotFoundError: No module named 'aqt.hooks_gen'
```

I guess Anki changes its module path from `hooks_gen` to `gui_hooks`.
⁩

**Comment by nayyala** [comment]
In addToGear.py change the line to:

from aqt.gui_hooks import deck_browser_will_show_options_menu
