### ISSUE TITLE
2.1.60 Error Loading

### ISSUE THREAD

**Issue by shmuelsash** [Arthur-Milchior/Anki-postpone-reviews#40]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Postpone cards review⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\shmue\AppData\Roaming\Anki2\addons21\1152543397\__init__.py", line 1, in <module>
    from . import addToBrowser, addToGear, addToMain
  File "C:\Users\shmue\AppData\Roaming\Anki2\addons21\1152543397\addToGear.py", line 2, in <module>
    from aqt.hooks_gen import deck_browser_will_show_options_menu
ModuleNotFoundError: No module named 'aqt.hooks_gen'
⁩

**Comment by sahmed251** [comment]
For those who get the error message when installing the add on. You have to delete the Anki app and then reinstall the latest version (2.1.6) of Anki from your laptop computer. Then install this add on. It should work.

**Comment by Arthur-Milchior** [comment]
That's strange. Normally, tere should be no reason you must delete te anki app.
